-- Supaa keybind-lock submap — Lua syntax (Hyprland >= 0.55, hyprland.lua).
--
-- Generated by the Supaa installer. Require it from your main
-- hyprland.lua rather than inlining it, so it can be cleanly removed
-- later (adjust the require/module path to match your own config layout
-- — see the Hyprland wiki's "Expanding functionality" page):
--
--   require("hypr-supaa")

-- ── Global escape hatch (submap_universal = true) ─────────────────────────────
--
-- Super+Shift+Q exits Supaa++ by running `supaa mode normal` directly.
-- This is an immediate, no-popup restore that works even when the Supaa
-- UI window does not have focus.  submap_universal=true ensures these binds
-- fire regardless of which submap is currently active.
--
-- Super+Escape is kept as a secondary alias.
hl.bind("SUPER SHIFT + Q", hl.dsp.exec_cmd("supaa mode normal"), { submap_universal = true })
hl.bind("SUPER + ESCAPE",  hl.dsp.exec_cmd("supaa mode normal"), { submap_universal = true })

-- ── Workspace-lock submap ──────────────────────────────────────────────────────
--
-- Intentionally empty: all other keybinds (SUPER+1..9, SUPER+arrow, etc.)
-- fall through to nothing while this submap is active — that absence IS the lock.
hl.define_submap("supaa_lock", function()
end)
